select
    purchase_id,
    purchase_datetime,
    customer_id,
    store_id,
    channel,
    payment_method,
    product_id,
    quantity,
    unit_price,
    discount_pct,
    net_amount,
    tax_amount,
    total_amount,
    "Year" as year_dt,
    "Quarter" as quarter_dt,
    "Month (Name)" as month_name,
    "Month (Number)" as month_number,
    unit_of_measure
from {{ source('raw', 'purchases') }}
